on: [push]

jobs:
  tooth:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.head_commit.message, 'enh(post)') }}
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Send toot to Mastodon
      id: mastodon
      uses: cbrgm/mastodon-github-action@v1
      with:
        message: ${{ github.event.head_commit.message }}
        visibility: "public"
      env:
        MASTODON_URL: ${{ secrets.MASTODON_URL }}
        MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
